import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '/admin/dashboard',
    title: 'Doanh thu',
    icon: 'bi bi-speedometer2',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/manage/tour',
    title: 'Tour',
    icon: 'bi bi-book',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/manage/account',
    title: 'Tài khoản',
    icon: 'bi bi-people',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/manage/booking',
    title: 'Booking',
    icon: 'bi bi-clipboard-check',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/alert',
    title: 'Alert',
    icon: 'bi bi-bell',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/badges',
    title: 'Badges',
    icon: 'bi bi-patch-check',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/buttons',
    title: 'Button',
    icon: 'bi bi-hdd-stack',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/card',
    title: 'Card',
    icon: 'bi bi-card-text',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/dropdown',
    title: 'Dropdown',
    icon: 'bi bi-menu-app',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/pagination',
    title: 'Pagination',
    icon: 'bi bi-dice-1',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/nav',
    title: 'Nav',
    icon: 'bi bi-pause-btn',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/component/table',
    title: 'Table',
    icon: 'bi bi-layout-split',
    class: '',
    extralink: false,
    submenu: [],
  },
  {
    path: '/admin/about',
    title: 'About',
    icon: 'bi bi-people',
    class: '',
    extralink: false,
    submenu: [],
  },
];
